export const ZARTEK_FOOD= 'ZARTEK_FOOD'
export const ZARTEK_FOOD_SUCCESS = 'ZARTEK_FOOD_SUCCESS'
export const ZARTEK_FOOD_FAILURE = 'ZARTEK_FOOD_FAILURE'
export const ZARTEK_FOOD_RESET = 'ZARTEK_FOOD_RESET'
